#!/bin/bash

echo OpenID provider:
read OPENID

awk -v openid="$OPENID" '
/^provider/ {$0 = "provider = " openid}
{print}
' /data/conf/openqa.ini > /tmp/openqa.ini.new
mv /tmp/openqa.ini.new /data/conf/openqa.ini

echo "The file now contains:"
cat /data/conf/openqa.ini
