#!/bin/bash

echo Key:
read KEY
echo Secret:
read SECRET

sed "s/key =.*/key = $KEY/" -i /data/conf/client.conf
sed "s/secret =.*/secret = $SECRET/" -i /data/conf/client.conf

echo "The file now contains:"
cat /data/conf/client.conf
