#!/usr/bin/perl -w
# This code is Copyright 2010 Bernhard M. Wiedemann
# and is licensed under the GNU General Public License version 2 or later.
# http://www.gnu.org/licenses/gpl-2.0.html

# This hardlinks iso images to more canonical names

use strict;

foreach my $fn (@ARGV) {
	my $newname=$fn;
	$newname=~s{.*/}{liveiso/};
	$newname=~s/\.(\w+)-([0-9.]+)-(Build[0-9.]+)/-$1-$2_$3/;
	$newname=~s/KDE4-UNSTABLE-Live/openSUSE-KDE4_UNSTABLE_LiveCD/;
	$newname=~s/Smeegol/openSUSE-Smeegol_LiveCD/;
	print "$fn $newname\n";
	link $fn,$newname;
}
