pull_request_rules:
  - name: automatic merge
    conditions:
      - and: &a1
          - base=master
          - -label~=^acceptance-tests-needed|not-ready
          - status-success=codecov/project
          - status-success=codecov/patch
          - "#check-success>=50"
          - status-success=static-check-containers
          - status-success=webui-docker-compose
          - "#check-failure=0"
          - "#check-pending=0"
          - linear-history
      - and:
          - "#approved-reviews-by>=2"
          - "#changes-requested-reviews-by=0"
          - "#review-requested=0"
    actions: &a2
      merge:
        method: merge
  - name: automatic merge on special label
    conditions:
      - and: *a1
      - label=merge-fast
    actions: *a2
  - name: automatic merge for dependency bot updates
    conditions:
      - and: *a1
      - author~=^os-autoinst-bot$
    actions: *a2
  - name: ask to resolve conflict
    conditions:
      - conflict
    actions:
      comment:
        message: This pull request is now in conflicts. Could you fix it? 🙏
  - name: automatic merge for dependabot updates
    conditions:
      - and: *a1
      - and:
          - base=main
          - author=dependabot[bot]
          - label=waited
    actions:
      merge:
        method: squash
  - name: Wait for some days before validating merge
    actions:
      label:
        add:
          - waited
        remove:
          - waiting
    conditions:
      - and:
          - updated-at<4 days ago
          - author=dependabot[bot]
queue_rules: []
merge_queue:
  status_comments: none
