codecov:
  branch: master
comment:
  behavior: default
  require_changes: true
# https://progress.opensuse.org/issues/88594
fixes:
  - "/home/circleci/openQA::"
coverage:
  round: down
  precision: 2
  status:
    changes: false
    project:
      default:
        target: 98
        threshold: 0
      fully_covered:
        target: 100.0
        threshold: 0
        paths:
          - lib/OpenQA/Client/
          - lib/OpenQA/Worker/
          - lib/OpenQA/Worker.pm
          - lib/OpenQA/Utils.pm
          - lib/OpenQA/WebAPI/Controller/File.pm
          - lib/OpenQA/WebAPI/Controller/Step.pm
          - lib/OpenQA/WebAPI/Controller/Test.pm
          - lib/OpenQA/WebAPI/Controller/API/V1/Iso.pm
          - lib/OpenQA/WebAPI/Controller/API/V1/Job.pm
          - lib/OpenQA/WebAPI/Controller/API/V1/Mm.pm
      tests:
        target: 100.0
        threshold: 0
        paths:
          - t/
    patch:
      default:
        target: 100.0
        threshold: 0
        branches: null
