codecov:
  branch: master
comment:
  behavior: default
  require_changes: true
# https://progress.opensuse.org/issues/88594
fixes:
  - "/home/circleci/openQA::"
coverage:
  range: 60..95
  round: down
  precision: 2
  status:
    changes: false
    project:
      default:
        target: 95.0
        threshold: 0.1
    patch:
      default:
        branches: null
