codecov:
  branch: master
comment:
  behavior: default
  require_changes: true
coverage:
  precision: 2
  range:
  - 60.0
  - 95.0
  round: down
  status:
    changes:
      default:
        branches: null
    project:
      default:
        target: 85.3
        threshold: 0.1
    patch:
      default:
        branches: null
