codecov:
  branch: master
comment:
  behavior: default
  require_changes: true
# https://progress.opensuse.org/issues/88594
fixes:
  - "/home/circleci/openQA::"
coverage:
  status:
    changes: false
    project:
      default: false
      tests:
        target: 98
        paths: "t/"
      app:
        paths: "!t/"
      absolute_path_test:
        paths:
          - /home/circleci/openQA/
    patch:
      default:
        branches: null
