codecov:
  branch: master
comment:
  behavior: default
  require_changes: true
coverage:
  precision: 2
  range:
  - 60.0
  - 95.0
  round: down
  notify:
    irc:
      default:
        server: chat.freenode.net
        channel: '##opensuse-factory'
        threshold: 0.01
  status:
    changes:
      default:
        branches: null
    project:
      default:
        target: auto
        threshold: 0.1
    patch:
      default:
        branches: null
