codecov:
  token: 058d4462-cb3c-455d-bb6d-3e6859f3de9e
  branch: master
comment:
  behavior: default
  require_changes: true
# https://progress.opensuse.org/issues/88594
fixes:
  - "/home/circleci/openQA::"
coverage:
  status:
    changes: false
    project:
      default:
        target: 98
      tests:
        target: 99.48
        paths:
          - t/
    patch:
      default:
        target: 100.0
        branches: null
