codecov:
  branch: master
comment:
  behavior: default
  require_changes: true
coverage:
  precision: 2
  range:
  - 60.0
  - 95.0
  round: down
  status:
    changes: no
    project:
      default:
        target: 87.8
        threshold: 0.1
    patch:
      default:
        branches: null
