codecov:
  branch: master
comment:
  behavior: default
  require_changes: true
coverage:
  precision: 2
  range:
  - 70.0
  - 100.0
  round: down
  notify:
    irc:
      default:
        server: chat.freenode.net
        channel: '##opensuse-factory'
  status:
    changes:
      default:
        branches: null
    project:
      default:
        target: 68
        only_pulls: true
    patch:
      default:
        branches: null
