codecov:
  branch: master
comment:
  behavior: default
  require_changes: true
# https://progress.opensuse.org/issues/88594
fixes:
  - "/home/circleci/openQA::"
coverage:
  status:
    changes: false
    project:
      default:
        target: 98
      fully_covered:
        target: 100.0
        paths:
          - lib/openQA/Worker
      tests:
        target: 100.0
        paths:
          - t/
    patch:
      default:
        target: 100.0
        branches: null
