#!/bin/bash
set -e
: ${DESTDIR:=/}
if ! test -w "$DESTDIR"; then
	echo "need write access to $DESTDIR!";
	exit 1
fi
d=$DESTDIR/var/lib/openqa
mkdir -p $d
rm -f $d/db
echo .quit | sqlite3 -init db.sql $d/db
chown wwwrun $d $d/db
