version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    cooldown:
      default-days: 7
    open-pull-requests-limit: 5
    groups:
      all-actions:
        patterns:
          - "*"
