{{ if .Values.cacheService -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "worker.fullname" . }}-cache
  labels:
    {{- include "worker.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.cacheLimit }}Gi
{{ end -}}
