apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "worker.fullname" . }}-configmap
  labels:
    {{- include "worker.labels" . | nindent 4 }}
data:
  workers_ini: |
    [global]
    HOST = http://{{ .Release.Name }}-openqa:9526
    WORKER_HOSTNAME = {{ .Release.Name }}-worker
    BACKEND = qemu
    {{ if .Values.workerClass -}}
    WORKER_CLASS = {{ .Values.workerClass }}
    {{ end -}}
    {{ if .Values.cacheService -}}
    CACHEDIRECTORY = /var/lib/openqa/cache
    CACHELIMIT = {{ .Values.cacheLimit }}
    CACHEWORKERS = 1

    [{{ .Values.openqa.host }}]
    TESTPOOLSERVER = rsync://{{ .Values.openqa.host }}/tests
    {{ end }}
  client_conf: |
    [localhost]
    key = {{ .Values.openqa.key }}
    secret = {{ .Values.openqa.secret }}

    [{{ .Release.Name }}-openqa]
    key = {{ .Values.openqa.key }}
    secret = {{ .Values.openqa.secret }}
