---
name: 'Perl author tests'

on: [push, pull_request]

jobs:
  perl-author-tests:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    name: Perl author tests
    container:
      image: registry.opensuse.org/devel/openqa/containers/os-autoinst_dev
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - run: |
          git config --system --add safe.directory "$GITHUB_WORKSPACE"
          make test-author
