---
name: 'Perl static checks'

on: [push, pull_request]

jobs:
  perl-lint-checks:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    name: "Perltidy"
    container:
      image: registry.opensuse.org/devel/openqa/containers/os-autoinst_dev
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - run: GITHUB_ACTIONS=1 make test-tidy
