---
name: 'Unit Tests'

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: perldocker/perl-tester
    steps:
      - uses: actions/checkout@v4
      - run: make test-t
