---
name: 'YAML-lint'

on: [push, pull_request]

jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    name: "YAML-lint"
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6
      - uses: docker://registry.opensuse.org/home/okurz/container/containers/tumbleweed:yamllint
        with:
          entrypoint: make
          args: test-yaml
