---
name: 'YAML-lint'

on: [push, pull_request]

jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    name: "YAML-lint"
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      - uses: docker://registry.opensuse.org/home/okurz/container/containers/tumbleweed:yamllint
        with:
          entrypoint: make
          args: test-yaml
