---
name: 'YAML-lint'

on: [push, pull_request]

jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    name: "YAML-lint"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - uses: docker://registry.opensuse.org/home/okurz/container/containers/tumbleweed:yamllint
        with:
          entrypoint: make
          args: test-yaml
