#!BuildTag: openqa_webui_lb
FROM opensuse/leap:15.3
LABEL maintainer Ivan Lausuch <ilausuch@suse.com>

# hadolint ignore=DL3037
RUN zypper ar -p 95 -f http://download.opensuse.org/repositories/devel:openQA/openSUSE_Leap_15.3 devel_openQA && \
    zypper ar -p 90 -f http://download.opensuse.org/repositories/devel:openQA:Leap:15.3/openSUSE_Leap_15.3 devel_openQA_Leap && \
    zypper --gpg-auto-import-keys ref && \
    zypper in -y --force-resolution openQA nginx && \
    zypper clean

COPY nginx-entrypoint.sh /entrypoint.sh
COPY nginx.conf /etc/nginx/nginx.conf.template

RUN chmod a+x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
