#!BuildTag: openqa_webui_lb
FROM opensuse/tumbleweed
LABEL maintainer Ivan Lausuch <ilausuch@suse.com>

# hadolint ignore=DL3037
RUN zypper ar -p 95 -f http://download.opensuse.org/repositories/devel:openQA/openSUSE_Tumbleweed devel_openQA && \
    zypper --gpg-auto-import-keys ref && \
    zypper in -y openQA nginx && \
    zypper clean

COPY nginx-entrypoint.sh /entrypoint.sh
COPY nginx.conf /etc/nginx/nginx.conf.template

RUN chmod a+x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
