# SPDX-License-Identifier: MIT
#!BuildTag: openqa_webui_lb:latest opensuse/openqa-webui-lb:latest opensuse/openqa-webui-lb:%PKG_VERSION% opensuse/openqa-webui-lb:%PKG_VERSION%.%RELEASE%
FROM opensuse/leap:16.0

# labelprefix=org.opensuse.openqa-webui-lb
LABEL org.opencontainers.image.title="openQA load-balancer webui container"
LABEL org.opencontainers.image.description="An openQA webui instance including NginX as a load balancer"
LABEL org.opencontainers.image.version="%PKG_VERSION%.%RELEASE%"
LABEL org.opensuse.reference="registry.opensuse.org/opensuse/openqa-webui:%PKG_VERSION%.%RELEASE%"
LABEL org.openbuildservice.disturl="%DISTURL%"
LABEL org.opencontainers.image.created="%BUILDTIME%"
# endlabelprefix

# hadolint ignore=DL3037
RUN zypper ar -p 95 -f http://download.opensuse.org/repositories/devel:openQA/16.0 devel_openQA && \
    zypper ar -p 90 -f http://download.opensuse.org/repositories/devel:openQA:Leap:16.0/16.0 devel_openQA_Leap && \
    zypper --gpg-auto-import-keys ref && \
    zypper in -y openQA nginx && \
    zypper clean

COPY nginx-entrypoint.sh /entrypoint.sh
COPY nginx.conf /etc/nginx/nginx.conf.template

RUN chmod a+x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
