#!BuildTag: openqa_webui_lb
FROM opensuse/tumbleweed
LABEL maintainer Ivan Lausuch <ilausuch@suse.com>

RUN zypper ar -p 95 -f http://download.opensuse.org/repositories/devel:openQA/openSUSE_Tumbleweed devel_openQA && \
    zypper --gpg-auto-import-keys ref && \
    zypper --non-interactive in --force-resolution openQA nginx

COPY nginx-entrypoint.sh /entrypoint.sh
COPY nginx.conf /etc/nginx/conf.d/default.conf.template

RUN chmod a+x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
