#!/bin/sh
# mv/cp to keep backlog of rootfs img

bd=backlog
max=19
imgdir=$1
name=$2

test `du -c $imgdir/l? $imgdir/? |tail -1|cut -f1` -eq 0 && exit 0 # nothing to backlog
rm -rf $bd/$max # delete oldest
for i in $(seq $max -1 1) ; do # rotate
	n=$(expr $i - 1)
	test -d $bd/$n || continue
	mv -f $bd/$n $bd/$i
done
mkdir -p $bd/0
cp -p --sparse=always $imgdir/l? $bd/0/
echo $name > $bd/0/name

true
