#!/bin/sh

ROOT_DIR="$0"
ROOT_DIR="`dirname "$ROOT_DIR"`" # Get rid of script
ROOT_DIR="`dirname "$ROOT_DIR"`" # Get to the git root
cd "$ROOT_DIR"

matches=`(find -name "*.p[lm]" -type f; ls script/{check_dependencies,client,initdb,openqa,worker}) | xargs grep -nP "^ *\t"`

if [ "$?" == "0" ] ; then
	echo -e "Bad indentation detected:\n"
	echo "$matches"
	exit 1
else
	echo "Indentation is valid."
fi
