#!/usr/bin/env perl

# Copyright 2015 SUSE LLC
# SPDX-License-Identifier: GPL-2.0-or-later

use Mojo::Base -strict;

use FindBin;
use lib "$FindBin::RealBin/../lib";

use OpenQA::Scheduler;
use OpenQA::Utils qw(service_port set_listen_address fix_top_level_help);

fix_top_level_help;

set_listen_address(service_port('scheduler'));
OpenQA::Scheduler::run;
