#!/usr/bin/env perl

# Copyright (C) 2014 SUSE LLC
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, see <http://www.gnu.org/licenses/>.

use warnings;
use Mojo::Base -strict;

use FindBin;
use lib "$FindBin::RealBin/../lib";

use OpenQA::WebAPI;
use OpenQA::Utils qw(service_port set_listen_address);

# allow up to 20GB - hdd images
$ENV{MOJO_MAX_MESSAGE_SIZE}   = 1024 * 1024 * 1024 * 20;
$ENV{MOJO_INACTIVITY_TIMEOUT} = 300;

# the default is EV, and this heavily screws with our children handling
$ENV{MOJO_REACTOR} = 'Mojo::Reactor::Poll';

set_listen_address(service_port('webui'));
OpenQA::WebAPI::run;

