#!/usr/bin/env perl

# Copyright (C) 2014 SUSE Linux Products GmbH
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, see <http://www.gnu.org/licenses/>.

use strict;
use warnings;

use FindBin;
BEGIN { unshift @INC, "$FindBin::Bin/../lib" }

$ENV{'MOJO_LISTEN'} ||= 'http://localhost:9526/';

# allow up to 20GB - hdd images
$ENV{MOJO_MAX_MESSAGE_SIZE}   = 1024 * 1024 * 1024 * 20;
$ENV{MOJO_INACTIVITY_TIMEOUT} = 300;
# the default is EV, and this heavily screws with our children handling
$ENV{MOJO_REACTOR} = 'Mojo::Reactor::Poll';

use OpenQA::WebAPI;

OpenQA::WebAPI::run;

# vim: set sw=4 sts=4 et:
