#!/usr/bin/env perl

# Copyright 2015-2020 SUSE LLC
# SPDX-License-Identifier: GPL-2.0-or-later

use Mojo::Base -strict;

use FindBin;
use lib "$FindBin::RealBin/../lib";

use OpenQA::WebSockets;
use OpenQA::Utils qw(service_port set_listen_address fix_top_level_help);

fix_top_level_help;

# allow up to 20GB - hdd images
$ENV{MOJO_MAX_MESSAGE_SIZE} = 1024 * 1024 * 1024 * 20;

set_listen_address(service_port('websocket'));
OpenQA::WebSockets::run;
