#!/usr/bin/env perl
# Copyright 2020 SUSE LLC
# SPDX-License-Identifier: GPL-2.0-or-later

use strict;
use warnings;

use FindBin;
use lib "$FindBin::RealBin/../lib";

use OpenQA::CLI;

@ARGV = () if ($ARGV[0] // '') =~ qr/^(-h|(--)?help)$/;

my $ret = OpenQA::CLI->new->run(@ARGV);
exit $ret unless $ENV{MOJO_HELP};
