#! /usr/bin/perl

# this script needs to be called periodically to reduce the size of the
# stored images 

use strict;
use File::Basename;
use File::Find;

sub optimize() { 
    return if $File::Find::name !~ m/\.png\.unoptimized$/;
    my ($name,$path,$suffix) = fileparse($File::Find::name, qw/.unoptimized/);
    print "NAME $File::Find::dir/$name\n";
    if(system("optipng", "-preserve", "-quiet", "-o2", "$path/$name") == 0) {
      unlink("$path/$name$suffix");
    }
}

find(\&optimize, "/var/lib/openqa/images");

