#!/bin/sh

TIDY_ARGS="-b -l=0"

if ! which perltidy > /dev/null 2>&1; then
    echo "No perltidy found, install it first!"
    exit 1
fi

ROOT_DIR="$0"
ROOT_DIR="`dirname "$ROOT_DIR"`" # Get rid of script
ROOT_DIR="`dirname "$ROOT_DIR"`" # Get to the git root
cd "$ROOT_DIR"

find . -name '*.p[lm]' -exec perltidy $TIDY_ARGS \{\} \;

find script/{check_dependencies,client,initdb,openqa,worker} -exec perltidy $TIDY_ARGS \{\} \;

find -name '*.bak' -delete

# vim: set ts=4 sw=4 sts=4 et:
