#!/usr/bin/perl

use strict;
use warnings;

use FindBin;
BEGIN { unshift @INC, "$FindBin::Bin/../lib", "$FindBin::Bin/../lib/WebQA/modules"}

$ENV{'MOJO_LISTEN'} ||= 'http://localhost:9526/';

# Start command line interface for application
require Mojolicious::Commands;
Mojolicious::Commands->start_app('WebQA');
