-- Convert schema '/home/okurz/local/os-autoinst/openQA/script/../dbicdh/_source/deploy/53/001-auto.yml' to '/home/okurz/local/os-autoinst/openQA/script/../dbicdh/_source/deploy/54/001-auto.yml':;

;
BEGIN;

;
ALTER TABLE jobs ALTER COLUMN TEST SET NOT NULL;

;
ALTER TABLE jobs ALTER COLUMN DISTRI SET NOT NULL;

;
ALTER TABLE jobs ALTER COLUMN DISTRI SET DEFAULT '';

;
ALTER TABLE jobs ALTER COLUMN VERSION SET NOT NULL;

;
ALTER TABLE jobs ALTER COLUMN VERSION SET DEFAULT '';

;
ALTER TABLE jobs ALTER COLUMN FLAVOR SET NOT NULL;

;
ALTER TABLE jobs ALTER COLUMN FLAVOR SET DEFAULT '';

;
ALTER TABLE jobs ALTER COLUMN ARCH SET NOT NULL;

;
ALTER TABLE jobs ALTER COLUMN ARCH SET DEFAULT '';

;
ALTER TABLE jobs ALTER COLUMN BUILD SET NOT NULL;

;
ALTER TABLE jobs ALTER COLUMN BUILD SET DEFAULT '';

;

COMMIT;
