{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "openqa.fullname" . }}-ingress
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.baseUrl }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ include "openqa.fullname" . }}
              port:
                name: webui
        - path: /api/v1/ws
          pathType: Prefix
          backend:
            service:
              name: {{ include "openqa.fullname" . }}
              port:
                name: websockets
        - path: /livehandler
          pathType: Prefix
          backend:
            service:
              name: {{ include "openqa.fullname" . }}
              port:
                name: livehandler
{{- end }}
