#!/usr/bin/env perl

# Copyright (C) 2014 SUSE Linux Products GmbH
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

BEGIN { unshift @INC, 'lib', 'lib/OpenQA/modules'; }

use strict;
use warnings;
use Data::Dump qw/pp dd/;
use openqa::distri::opensuse qw(generate_jobs);

use Test::More;

my @testdata = (
    {
        iso => "openSUSE-Factory-DVD-x86_64-Build0725-Media.iso",
        params => [
            {
                ARCH        => 'x86_64',
                BUILD       => '0725',
                DESKTOP     => "kde",
                DISTRI      => "opensuse",
                DVD         => 1,
                FLAVOR      => "DVD",
                INSTALLONLY => 1,
                ISO         => "openSUSE-Factory-DVD-x86_64-Build0725-Media.iso",
                ISO_MAXSIZE => '4700372992',
                PRIO        => 45,
                RAIDLEVEL   => 0,
                TEST        => 'RAID0',
                VERSION     => "Factory",
            },
            {
                ARCH        => 'x86_64',
                BUILD       => '0725',
                DESKTOP     => "kde",
                DISTRI      => "opensuse",
                DVD         => 1,
                FLAVOR      => "DVD",
                INSTALLONLY => 1,
                ISO         => "openSUSE-Factory-DVD-x86_64-Build0725-Media.iso",
                ISO_MAXSIZE => '4700372992',
                PRIO        => 46,
                RAIDLEVEL   => 1,
                TEST        => 'RAID1',
                VERSION     => "Factory",
            },
            {
                ARCH        => 'x86_64',
                BUILD       => '0725',
                DESKTOP     => "kde",
                DISTRI      => "opensuse",
                DVD         => 1,
                FLAVOR      => "DVD",
                INSTALLONLY => 1,
                ISO         => "openSUSE-Factory-DVD-x86_64-Build0725-Media.iso",
                ISO_MAXSIZE => '4700372992',
                PRIO        => 46,
                RAIDLEVEL   => 10,
                TEST        => 'RAID10',
                VERSION     => "Factory",
            },
            {
                ARCH        => 'x86_64',
                BUILD       => '0725',
                DESKTOP     => "kde",
                DISTRI      => "opensuse",
                DVD         => 1,
                FLAVOR      => "DVD",
                INSTALLONLY => 1,
                ISO         => "openSUSE-Factory-DVD-x86_64-Build0725-Media.iso",
                ISO_MAXSIZE => '4700372992',
                PRIO        => 46,
                RAIDLEVEL   => 5,
                TEST        => 'RAID5',
                VERSION     => "Factory",
            },
            {
                ARCH        => 'x86_64',
                BUILD       => '0725',
                BTRFS     => 1,
                DESKTOP   => "kde",
                DISTRI    => "opensuse",
                DVD       => 1,
                ENCRYPT   => 1,
                FLAVOR    => "DVD",
                HDDSIZEGB => 20,
                ISO       => "openSUSE-Factory-DVD-x86_64-Build0725-Media.iso",
                ISO_MAXSIZE => '4700372992',
                LVM       => 1,
                NICEVIDEO => 1,
                PRIO      => 45,
                TEST      => "btrfscryptlvm",
                VERSION   => "Factory",
            },
            {
                ARCH        => 'x86_64',
                BUILD       => '0725',
                DESKTOP            => "kde",
                DISTRI             => "opensuse",
                DVD                => 1,
                ENCRYPT            => 1,
                FLAVOR             => "DVD",
                ISO                => "openSUSE-Factory-DVD-x86_64-Build0725-Media.iso",
                ISO_MAXSIZE => '4700372992',
                LVM                => 1,
                NICEVIDEO          => 1,
                PRIO               => 45,
                REBOOTAFTERINSTALL => 0,
                TEST               => "cryptlvm",
                VERSION            => "Factory",
            },
            {
                ARCH        => 'x86_64',
                BUILD       => '0725',
                DESKTOP => "kde",
                DISTRI  => "opensuse",
                DOCRUN  => 1,
                DVD     => 1,
                FLAVOR  => "DVD",
                ISO     => "openSUSE-Factory-DVD-x86_64-Build0725-Media.iso",
                ISO_MAXSIZE => '4700372992',
                PRIO    => 55,
                QEMUVGA => "std",
                TEST    => "doc",
                VERSION => "Factory",
            },
            {
                ARCH        => 'x86_64',
                BUILD       => '0725',
                DESKTOP    => "kde",
                DISTRI     => "opensuse",
                DUALBOOT   => 1,
                DVD        => 1,
                FLAVOR     => "DVD",
                HDD_1      => "Windows-8.hda",
                HDDMODEL   => "ide-hd",
                HDDVERSION => "Windows 8",
                ISO        => "openSUSE-Factory-DVD-x86_64-Build0725-Media.iso",
                ISO_MAXSIZE => '4700372992',
                NUMDISKS   => 1,
                PRIO       => 45,
                TEST       => "dual_windows8",
                VERSION    => "Factory",
            },
            {
                ARCH        => 'x86_64',
                BUILD       => '0725',
                DESKTOP => "gnome",
                DISTRI  => "opensuse",
                DVD     => 1,
                FLAVOR  => "DVD",
                ISO     => "openSUSE-Factory-DVD-x86_64-Build0725-Media.iso",
                ISO_MAXSIZE => '4700372992',
                LVM     => 1,
                PRIO    => 40,
                TEST    => "gnome",
                VERSION => "Factory",
            },
            {
                ARCH        => 'x86_64',
                BUILD       => '0725',
                BTRFS     => 1,
                DESKTOP   => "gnome",
                DISTRI    => "opensuse",
                DVD       => 1,
                FLAVOR    => "DVD",
                HDDSIZEGB => 20,
                ISO       => "openSUSE-Factory-DVD-x86_64-Build0725-Media.iso",
                ISO_MAXSIZE => '4700372992',
                LVM       => 1,
                PRIO      => 45,
                TEST      => "gnome+btrfs",
                VERSION   => "Factory",
            },
            {
                ARCH        => 'x86_64',
                BUILD       => '0725',
                DESKTOP => "gnome",
                DISTRI  => "opensuse",
                DVD     => 1,
                FLAVOR  => "DVD",
                ISO     => "openSUSE-Factory-DVD-x86_64-Build0725-Media.iso",
                ISO_MAXSIZE => '4700372992',
                LAPTOP  => 1,
                PRIO    => 45,
                TEST    => "gnome+laptop",
                VERSION => "Factory",
            },
            {
                ARCH        => 'x86_64',
                BUILD       => '0725',
                DESKTOP => "kde",
                DISTRI  => "opensuse",
                DVD     => 1,
                FLAVOR  => "DVD",
                ISO     => "openSUSE-Factory-DVD-x86_64-Build0725-Media.iso",
                ISO_MAXSIZE => '4700372992',
                PRIO    => 35,
                TEST    => "kde",
                VERSION => "Factory",
            },
            {
                ARCH        => 'x86_64',
                BUILD       => '0725',
                BTRFS     => 1,
                DESKTOP   => "kde",
                DISTRI    => "opensuse",
                DVD       => 1,
                FLAVOR    => "DVD",
                HDDSIZEGB => 20,
                ISO       => "openSUSE-Factory-DVD-x86_64-Build0725-Media.iso",
                ISO_MAXSIZE => '4700372992',
                PRIO      => 45,
                TEST      => "kde+btrfs",
                VERSION   => "Factory",
            },
            {
                ARCH        => 'x86_64',
                BUILD       => '0725',
                DESKTOP => "kde",
                DISTRI  => "opensuse",
                DVD     => 1,
                FLAVOR  => "DVD",
                ISO     => "openSUSE-Factory-DVD-x86_64-Build0725-Media.iso",
                ISO_MAXSIZE => '4700372992',
                LAPTOP  => 1,
                PRIO    => 45,
                TEST    => "kde+laptop",
                VERSION => "Factory",
            },
            {
                ARCH        => 'x86_64',
                BUILD       => '0725',
                DESKTOP => "kde",
                DISTRI  => "opensuse",
                DVD     => 1,
                FLAVOR  => "DVD",
                ISO     => "openSUSE-Factory-DVD-x86_64-Build0725-Media.iso",
                ISO_MAXSIZE => '4700372992',
                PRIO    => 40,
                TEST    => "kde+usb",
                USBBOOT => 1,
                VERSION => "Factory",
            },
            {
                ARCH        => 'x86_64',
                BUILD       => '0725',
                DESKTOP => "lxde",
                DISTRI  => "opensuse",
                DVD     => 1,
                FLAVOR  => "DVD",
                ISO     => "openSUSE-Factory-DVD-x86_64-Build0725-Media.iso",
                ISO_MAXSIZE => '4700372992',
                LVM     => 1,
                PRIO    => 44,
                TEST    => "lxde",
                VERSION => "Factory",
            },
            {
                ARCH        => 'x86_64',
                BUILD       => '0725',
                DESKTOP => "minimalx",
                DISTRI  => "opensuse",
                DVD     => 1,
                FLAVOR  => "DVD",
                ISO     => "openSUSE-Factory-DVD-x86_64-Build0725-Media.iso",
                ISO_MAXSIZE => '4700372992',
                PRIO    => 40,
                TEST    => "minimalx",
                VERSION => "Factory",
            },
            {
                ARCH        => 'x86_64',
                BUILD       => '0725',
                BTRFS     => 1,
                DESKTOP   => "minimalx",
                DISTRI    => "opensuse",
                DVD       => 1,
                FLAVOR    => "DVD",
                HDDSIZEGB => 20,
                ISO       => "openSUSE-Factory-DVD-x86_64-Build0725-Media.iso",
                ISO_MAXSIZE => '4700372992',
                PRIO      => 45,
                TEST      => "minimalx+btrfs",
                VERSION   => "Factory",
            },
            {
                ARCH        => 'x86_64',
                BUILD       => '0725',
                BTRFS       => 1,
                DESKTOP     => "minimalx",
                DISTRI      => "opensuse",
                DVD         => 1,
                FLAVOR      => "DVD",
                HDDSIZEGB   => 20,
                INSTALLONLY => 1,
                ISO         => "openSUSE-Factory-DVD-x86_64-Build0725-Media.iso",
                ISO_MAXSIZE => '4700372992',
                PRIO        => 45,
                TEST        => "minimalx+btrfs+nosephome",
                TOGGLEHOME  => 1,
                VERSION     => "Factory",
            },
            {
                ARCH        => 'x86_64',
                BUILD       => '0725',
                DESKTOP => "kde",
                DISTRI => "opensuse",
                DOCRUN => 1,
                DVD => 1,
                FLAVOR => "DVD",
                ISO => "openSUSE-Factory-DVD-x86_64-Build0725-Media.iso",
                ISO_MAXSIZE => '4700372992',
                NICEVIDEO => 1,
                PRIO => 45,
                REBOOTAFTERINSTALL => 0,
                SCREENSHOTINTERVAL => 0.25,
                TEST => "nice",
                VERSION => "Factory",
            },
            {
                ARCH        => 'x86_64',
                BUILD       => '0725',
                DESKTOP     => "kde",
                DISTRI      => "opensuse",
                DVD         => 1,
                FLAVOR      => "DVD",
                INSTALLONLY => 1,
                ISO         => "openSUSE-Factory-DVD-x86_64-Build0725-Media.iso",
                ISO_MAXSIZE => '4700372992',
                NICEVIDEO   => 1,
                PRIO        => 45,
                QEMUCPUS    => 4,
                TEST        => "smp",
                VERSION     => "Factory",
            },
            {
                ARCH        => 'x86_64',
                BUILD       => '0725',
                DESKTOP   => "kde",
                DISTRI    => "opensuse",
                DVD       => 1,
                FLAVOR    => "DVD",
                ISO       => "openSUSE-Factory-DVD-x86_64-Build0725-Media.iso",
                ISO_MAXSIZE => '4700372992',
                NICEVIDEO => 1,
                PRIO      => 45,
                SPLITUSR  => 1,
                TEST      => "splitusr",
                VERSION   => "Factory",
            },
            {
                ARCH        => 'x86_64',
                BUILD       => '0725',
                DESKTOP   => "textmode",
                DISTRI    => "opensuse",
                DVD       => 1,
                FLAVOR    => "DVD",
                ISO       => "openSUSE-Factory-DVD-x86_64-Build0725-Media.iso",
                ISO_MAXSIZE => '4700372992',
                PRIO      => 35,
                TEST      => "textmode",
                VERSION   => "Factory",
                VIDEOMODE => "text",
            },
            {
                ARCH        => 'x86_64',
                BUILD       => '0725',
                BTRFS     => 1,
                DESKTOP   => "textmode",
                DISTRI    => "opensuse",
                DVD       => 1,
                FLAVOR    => "DVD",
                HDDSIZEGB => 20,
                ISO       => "openSUSE-Factory-DVD-x86_64-Build0725-Media.iso",
                ISO_MAXSIZE => '4700372992',
                PRIO      => 45,
                TEST      => "textmode+btrfs",
                VERSION   => "Factory",
                VIDEOMODE => "text",
            },
            {
                ARCH        => 'x86_64',
                BUILD       => '0725',
                DESKTOP     => "kde",
                DISTRI      => "opensuse",
                DVD         => 1,
                FLAVOR      => "DVD",
                INSTALLONLY => 1,
                ISO         => "openSUSE-Factory-DVD-x86_64-Build0725-Media.iso",
                ISO_MAXSIZE => '4700372992',
                PRIO        => 40,
                QEMUCPU     => "qemu64",
                TEST        => "uefi",
                UEFI        => 1,
                VERSION     => "Factory",
            },
            {
                ARCH        => 'x86_64',
                BUILD       => '0725',
                DESKTOP    => "kde",
                DISTRI     => "opensuse",
                DVD        => 1,
                FLAVOR     => "DVD",
                HDD_1      => "openSUSE-12.1-x86_64.hda",
                HDDVERSION => "openSUSE-12.1",
                ISO        => "openSUSE-Factory-DVD-x86_64-Build0725-Media.iso",
                ISO_MAXSIZE => '4700372992',
                PRIO       => 45,
                TEST       => "update_121",
                UPGRADE    => 1,
                VERSION    => "Factory",
            },
            {
                ARCH        => 'x86_64',
                BUILD       => '0725',
                DESKTOP    => "kde",
                DISTRI     => "opensuse",
                DVD        => 1,
                FLAVOR     => "DVD",
                HDD_1      => "openSUSE-12.2-x86_64.hda",
                HDDVERSION => "openSUSE-12.2",
                ISO        => "openSUSE-Factory-DVD-x86_64-Build0725-Media.iso",
                ISO_MAXSIZE => '4700372992',
                PRIO       => 45,
                TEST       => "update_122",
                UPGRADE    => 1,
                VERSION    => "Factory",
            },
            {
                ARCH        => 'x86_64',
                BUILD       => '0725',
                DESKTOP    => "kde",
                DISTRI     => "opensuse",
                DVD        => 1,
                FLAVOR     => "DVD",
                HDD_1      => "openSUSE-12.3-x86_64.hda",
                HDDVERSION => "openSUSE-12.3",
                ISO        => "openSUSE-Factory-DVD-x86_64-Build0725-Media.iso",
                ISO_MAXSIZE => '4700372992',
                PRIO       => 45,
                TEST       => "update_123",
                UPGRADE    => 1,
                VERSION    => "Factory",
            },
            {
                ARCH        => 'x86_64',
                BUILD       => '0725',
                DESKTOP => "xfce",
                DISTRI  => "opensuse",
                DVD     => 1,
                FLAVOR  => "DVD",
                ISO     => "openSUSE-Factory-DVD-x86_64-Build0725-Media.iso",
                ISO_MAXSIZE => '4700372992',
                PRIO    => 44,
                TEST    => "xfce",
                VERSION => "Factory",
            },
        ],
    },
);

for my $t (@testdata) {
    my $params = openqa::distri::opensuse->generate_jobs({}, iso => $t->{iso});
    if ($t->{params}) {
        SKIP: {
            skip "number of jobs does not match", $#{$t->{params}} unless is(scalar @{$t->{params}}, scalar @$params);

            for my $i (0 .. @{$t->{params}}) {
                is_deeply($params->[$i], $t->{params}->[$i]);
            }
        }
    } else {
        ok(!defined $params, $t->{iso});
    }
}

done_testing;
