#!/bin/sh -e

KEEP_DB="${KEEP_DB:-0}"
DIR=$1
if test -z "$DIR"; then
    DIR=$(mktemp -d)
else
    DIR=$(readlink -f "$DIR")
    if test "$KEEP_DB" = "0"; then
        if test -d "$DIR"; then
            test -e "$DIR"/postmaster.pid && pg_ctl -D "$DIR" stop
            rm -r "$DIR"
        fi
    else
        echo "Re-using existing database in $DIR because KEEP_DB is set to 1."
        exit 0
    fi
fi
initdb --auth-local=peer -N "$DIR" -U "$(id -u -n)"
(echo "listen_addresses=''"
echo "unix_socket_directories='$DIR'"
echo "fsync=off"
echo "full_page_writes=off") >> "$DIR"/postgresql.conf

LOGDIR="$DIR/log"
LOGFILE="${LOGFILE:-"$LOGDIR/postgresql-openqa-test.log"}"
echo "PostgreSQL logs will be stored in $LOGFILE."

mkdir -p "$LOGDIR"
pg_ctl -D "$DIR" -l "$LOGFILE" start
createdb -h "$DIR" openqa_test

echo "Now export TEST_PG like:"
echo ""
echo "  export TEST_PG='DBI:Pg:dbname=openqa_test;host=$DIR'"
echo ""
echo " and if you don't need it anymore, use pg_ctl -D $DIR stop"
