#!/bin/sh
# mv/cp to keep backlog of rootfs img

bd=/space2/opensuse/backlog/
max=9
imgdir=$1
name=$2

test -n $LIVETEST && exit 0 # nothing to backlog
rm -rf $bd/$max # delete oldest
for i in $(seq $max -1 1) ; do # rotate
	n=$(expr $i - 1)
	mv -f $bd/$n $bd/$i
done
mkdir -p $bd/0
cp -p --sparse=always $imgdir/l? $bd/0/
echo $name > $bd/0/name

true
