#!/usr/bin/perl -w
# This code is Copyright 2010 Bernhard M. Wiedemann
# and is licensed under the GNU General Public License version 2 or later.
# http://www.gnu.org/licenses/gpl-2.0.html

# This execs a program, passing to it a pipe that will not block

use strict;
alarm(900);

pipe READHANDLE,WRITEHANDLE;
$SIG{PIPE}=$SIG{CHLD}=sub{exit 0};
my $pid=fork();
if($pid==0) {
	close WRITEHANDLE;
	open(STDIN, ">&", \*READHANDLE) or die $!;
	exec @ARGV or die $!;
} else {
	close READHANDLE;
	select WRITEHANDLE;
	$|=1;
	while(sleep 10) {
		print " ";
	}
}
