#!/bin/bash -e

# Navigate to the docs directory
cd "$(dirname "${BASH_SOURCE[0]}")/../docs"
mkdir -p ./build/

if [[ ! -e ./build/images ]]; then
    ln -s ../images build/images
fi

export BUNDLE_PATH=./vendor/

# Make sure dependencies exist
bundle install

# Run asciidoc
bundle exec asciidoctor -o build/index.html ./index.asciidoc -d book
