#!/bin/bash
set -e
: ${DESTDIR:=/}
if ! test -w "$DESTDIR"; then
	echo "need write access to $DESTDIR!";
	exit 1
fi
d=$DESTDIR/var/lib/openqa/db
mkdir -p $d
rm -f $d/db.sqlite
echo .quit | sqlite3 -init ${0%/*}/db.sql $d/db.sqlite
chown geekotest $d $d/db.sqlite
