#!/usr/bin/perl -w

BEGIN {
    use FindBin qw($Bin);
    use lib "$Bin/../lib", "$Bin/../lib/OpenQA/modules";
}

use strict;

use openqa ();

use Schema::Schema;

my $schema = openqa::connect_db();

$schema->deploy({ add_drop_table => 1 });
