#!/bin/sh -xe
# %s/\$@/\$out/g
# %s/\$</\$in/g
	basetestname=`perl -e '$_=shift;s/(?:-Media)?.iso$//;s%.*/%%;print' $in`
	baseoutname=`perl -e '$_=shift;s/\.ogv$//;s%.*/%%;print' $out`
	test -z "$basetestname" && exit 1
	test -z "$testdir" && exit 2
	test -z "$in" -o -z "$out" && exit 3
	echo in=$in out=$out
	#trap "rm -f $out" EXIT # clean up in case of errors
	sleep 1 # let date be higher than a previous test
	touch $out $out.autoinst.txt # prevent cron going in here during test
	echo `date` starting to create $out >>$L
	(pwd=`pwd`; cd ${testdir} ; /usr/local/bin/withlock kvm.lock ../perl/autoinst/tools/isotovideo $pwd/$in)
	echo `date` finished to create $out >>$L
	mv -f ${testdir}/currentautoinst-log.txt $out.autoinst.txt
	mv -f ${testdir}/video/$basetestname.ogv $out
	#trap "" EXIT
	rm -rf testresults/$baseoutname
	mv ${testdir}/testresults/$basetestname testresults/$baseoutname || true

