#!/bin/sh -xe
# %s/\$@/\$out/g
# %s/\$</\$in/g
	test -z "$testdir" && exit 2
	test -z "$in" -o -z "$out" && exit 3
	basetestname=`perl -e '$_=shift;s/(?:-Media)?.iso$//;s%.*/%%;print' $in`
	test -z "$basetestname" && exit 1
	baseoutname=`perl -e '$_=shift;s/\.ogv$//;s%.*/%%;print' $out`
	echo in=$in out=$out

	# some tests do not need to be run everytime
	for f in test.rules/* ; do
		. $f
	done

	#trap "rm -f $out" EXIT # clean up in case of errors
	sleep 1 # let date be higher than a previous test
	test -n "$out" && rm -rf "$out" || true
	mkdir ${testdir}/testresults/$basetestname # prevent cron going in here during test - future
	mkdir -p $out # prevent cron going in here during test
	rm -f schedule.d/$baseoutname
	ln -s ../${testdir}/testresults/$basetestname testresults/$baseoutname || true
	echo `date` starting to create $out >>$L
	#echo $basetestname | grep -q ^openSUSE- && export DISTRI=opensuse
	pwd=`pwd`
	if which isotovideo > /dev/null 2>&1 ; then
		isotovideo="isotovideo"
	else
		isotovideo="$pwd/perl/autoinst/tools/isotovideo"
	fi
	set +e # don't die from here on to make sure the testresults get collected
	(cd ${testdir} ; echo $baseoutname > testname ; withlock kvm.lock $isotovideo $pwd/$in )
	#XXX reenable tools/backlog ${testdir}/raid/ $baseoutname
	echo `date` finished to create $out >>$L
	mv -f ${testdir}/autoinst-log.txt ${testdir}/testresults/$basetestname/autoinst-log.txt
	#trap "" EXIT
	rm -f testresults/$baseoutname
	mv ${testdir}/testresults/$basetestname testresults/$baseoutname || true
	tools/notify $baseoutname || true
	if echo "$baseoutname" | grep -q 'archlinux' ; then
		tools/notify_archlinux.pl $baseoutname || true
	fi

