#!/bin/sh -e
# shellcheck disable=SC2048,SC2086

RETRY="${RETRY:-3}"
STABILITY_ALLOW_FAILURE="${STABILITY_ALLOW_FAILURE:-0}"
STABILITY_TEST="${STABILITY_TEST:-0}"
# Pass a hook command which is executed if a retry occurs
HOOK="${HOOK:-}"
EXPONENTIAL=${EXPONENTIAL:-1}
SLEEP="${SLEEP:-0}"

run_once() {
    "$@"
}

if [ "$RETRY" = "0" ]; then
    run_once "$@"
else
    n=1
    FAILURE_COUNTER=0
    while :; do
        if [ "$STABILITY_TEST" = "0" ]; then
            [ $n -le "$RETRY" ] || exit 1
            [ $n -eq 0 ] || echo "Retry $n of $RETRY …"
            run_once "$@" && break
        else
            [ $n -le "$RETRY" ] || exit 0
            if ! run_once "$@"; then
                if [ "$STABILITY_ALLOW_FAILURE" = "1" ]; then
                    FAILURE_COUNTER=$((FAILURE_COUNTER + 1))
                else
                    exit 1
                fi
            fi
            MESSAGE="Rerun $n of $RETRY …"
            if [ "$STABILITY_ALLOW_FAILURE" = "1" ]; then
                FAILURE_PERCENTAGE=$((FAILURE_COUNTER * 100 / n))
                MESSAGE="$MESSAGE with failures: $FAILURE_COUNTER ($FAILURE_PERCENTAGE%)"
            fi
            echo "$MESSAGE"
        fi
        if [ -n "$HOOK" ]; then
            echo "Calling retry hook $HOOK"
            RETRY_ATTEMPT=$n "$HOOK"
        fi
        n=$((n + 1))
        echo "Retrying after sleeping ${SLEEP}s …" >&2
        sleep "$SLEEP"
        [ -n "$EXPONENTIAL" ] && SLEEP=$((SLEEP * EXPONENTIAL))
    done
fi
