#!/bin/bash

set -euo pipefail

for i in webui worker; do
  (
    cd container/$i/ &&
     for retry in {2..0}; do sudo docker-compose build && break; echo "Remaining retries $retry"; done &&
    sudo docker-compose up -d &&
    (docker-compose ps --services --filter status=stopped | grep "^[[:space:]]*$") || (docker-compose logs; sudo docker-compose ps; exit 1)
  ) || exit 1;
done
