#!/bin/bash
set -euo pipefail

which helm > /dev/null || echo "Error: Helm is not installed"
which ct > /dev/null || echo "Error: ct is not installed"

cd container/helm

ct_extra=(--helm-extra-set-args "--set=gateway.enabled=false --set=image.pullPolicy=IfNotPresent --set=worker.image.pullPolicy=IfNotPresent")
ct_install_args=()
[[ "${1:-lint}" != "lint" ]] && ct_install_args=("${ct_extra[@]}")
ct "${1:-lint}" --debug --all --config ct.yaml "${ct_install_args[@]}"
