#!/bin/sh
dir=$1
shift
video=$1
shift

mkdir -p $dir/tmp/
cp -a /space/geekotest/opensuse/perl/autoinst/tools/ppmtompg $dir/tmp/

cat > $dir/tmp/init <<EOF
#!/bin/sh
cd /host
echo starting encoder
./tmp/ppmtompg qemuscreenshot $video
echo encoder returned \$?
sync
/sbin/halt -n -f -p
EOF
chmod a+x $dir/tmp/init

img=/space/bernhard/img/opensuse-113-32.img ; rootp=2
img=/space/bernhard/img/lenny32.img ; rootp=1

# con0=fd:0,fd:1
echo encoding with ffmpeg2theora within user-mode-linux...
# using perl-pipe because ffmpeg will sometimes block if stdin is closed
perl -e 'alarm 500;$|=1;while(sleep(10)){print " "}' | linux ubda=$img root=/dev/ubda$rootp mem=600M panic=30 raid=noautodetect con=fd:0,fd:1 init=/usr/local/sbin/hostinit hostinit=/host/tmp/init hostfs=$dir $*

rm -f $dir/tmp/*
