#!/bin/sh
dir=$1
shift
video=$1
shift

mkdir -p $dir/tmp/
cp -a /space/geekotest/opensuse/perl/autoinst/tools/ppmtompg $dir/tmp/

cat > $dir/tmp/init <<EOF
#!/bin/sh
cd /host
./tmp/ppmtompg qemuscreenshot $video
sync
/sbin/halt -n -f -p
EOF
chmod a+x $dir/tmp/init

img=/space/bernhard/img/opensuse-113-32.img ; rootp=2
img=/space/bernhard/img/lenny32.img ; rootp=1

# con0=fd:0,fd:1
echo encoding with ffmpeg2theora within user-mode-linux...
# using con=null/none because other console types will block in cron
linux ubda=$img root=/dev/ubda$rootp mem=600M panic=30 raid=noautodetect con0=fd:0,fd:1 con=null init=/usr/local/sbin/hostinit hostinit=/host/tmp/init hostfs=$dir $* </dev/null 1>&2

rm -f $dir/tmp/*
