#!/usr/bin/perl -w
# This code is Copyright 2010 Bernhard M. Wiedemann
# and is licensed under the GNU General Public License version 2 or later.
# http://www.gnu.org/licenses/gpl-2.0.html

# This code decides if a release is good enough to be snapshotted
# returning non-zero on failure

use strict;
use lib "/srv/www/cgi-bin/modules";
use awstandard;

my $buildnr;
for my $i (<factory-tested/iso/*.iso>) {
	$i=~m/-Build(\d{4})-Media\.iso$/;
	my $b=$1;
	if(!$buildnr) {$buildnr=$b}
	if($b ne $buildnr) {warn "error: inconsistent build numbers '$b'!='$buildnr' in iso filenames"}
}
my $lastbuildnrfilename="/var/tmp/lastfactorysnapshotisobuildnr";
awstandard::set_file_content($lastbuildnrfilename,$buildnr);

