Testing openSUSE
================

Easiest way to start using openQA is to start testing openSUSE as we have
everything setup and prepared to ease the initial deployment. If you want to
play deeper, you can configure whole openQA manually from scratch, but this
document should help you to get started faster.

Getting tests
-------------

First you need to get actual tests. You can get openSUSE tests and needles (the
expected results) from 
https://github.com/os-autoinst/os-autoinst-needles-opensuse[GitHub]. It belongs
to the +/var/lib/os-autoinst/tests+ directory. To make it easier, you can just
run

[source,sh]
--------------------------------------------------------------------------------
/usr/lib/os-autoinst/tools/fetchneedles
--------------------------------------------------------------------------------

Which will download the tests to the correct location and will set correct
rights as well.

Getting openQA configuration
----------------------------

To get everything configured to actually run the tests, there is a plenty of
options to set in admin interface. If you plan to tes openSUSE Factory, using
tests mentioned in previous section, easiest way to get started is the
following command:

[source,sh]
--------------------------------------------------------------------------------
cd /usr/share/openqa
./script/load_fixture lib/OpenQA/modules/openqa/distri/opensuse-fixtures.pl
--------------------------------------------------------------------------------

This will load some default settings that were used at some point of time in
openSUSE production openQA. Therefor those should work reasonably well with
openSUSE tests and needles.

Adding new iso to test
----------------------

To start testing new ISO put it in +/var/lib/openqa/factory/iso+ and call
following commands:

[source,sh]
--------------------------------------------------------------------------------
# Run the first test
/usr/share/openqa/script/client isos post \
         iso=openSUSE-Factory-NET-x86_64-Build0053-Media.iso tests=minimalx
--------------------------------------------------------------------------------

WARNING: Using only iso name in 'client' command and saving it in
+/var/lib/openqa/factory/iso+ is recommended as is using Factory iso. To use
different iso, you would need to to make sure it is recognizable by openQA. See
how naming is being parsed in +lib/OpenQA/modules/openqa/distri/opensuse.pm+

