openQA pitfalls
===============
:author: openSUSE Team at SUSE
:toc:


Needle editing
==============

- if a new needle is created based on a failed test, the new needle
  will not be listed in old tests.
- if an existing needle is updated with a new image or different
  areas, the old test will display the new needle which might be
  confusing
- if a needle is deleted, old tests may display an error when viewing
  them in the web UI.

DNS
===

You can use the environement variable +OPENQA_HOST+ from your perl test
scripts, so they can communicate with the real host. This variable will
expand to the value passed to the worker. You can configure this value for
example with

  HOST = http://www.example.com:9526

in +/etc/openqa/workers.ini+.

However, for that to work, you will need some DNS server to resolve the
domain name you chose to an IP address. Furthermore, the address of that
DNS server needs to be listed as the first entry in the host's +/etc/resolv.conf+
file, since it is the one that QEmu will pick up to set up its "user mode
networking".

IPv6
====

www.opensuse.org's openid provider may have trouble with IPv6. openQA shows a message like this:

  no_identity_server: Could not determine ID provider from URL.

To avoid that switch off IPv6 or add a special route that prevents the system
from trying to use IPv6 with www.opensuse.org:

--------------------------------------------------------------------------------
ip -6 r a to unreachable 2600:806:310::100/128
--------------------------------------------------------------------------------
