#!/usr/bin/perl -w
use strict;
use CGI ":standard";
use FindBin;
use lib "$FindBin::Bin/modules";
use awstandard;
use sort_list;
use openqa;
use Scheduler ();
use Text::MicroTemplate "encoded_string";
use Text::MicroTemplate::Extended;

# This tool is specific to openSUSE
# to enable the Release Team to see the quality at a glance

my $fn=$ENV{PATH_INFO};
if($fn=~m/\.\./) {print header(-status=>403)."invalid path"; exit 0; }
$fn=~s%^.*/%%;
my $build;
if ($fn =~ /Build(\d+)$/) {
    $build = $1;
} else {
    print header(-status=>403)."invalid build";
    exit 0;
}

my @configs=();
my %archs=();
my %results=();

sub store_result {
	my ($config,$type,$arch,$result) = @_;

	# Populate @configs and %archs
	push(@configs, $config) unless ($config ~~ @configs); # manage xxx.0, xxx.1 (we only want the most recent one)
	$archs{$type} = [] unless $archs{$type};
	push(@{$archs{$type}}, $arch) unless ($arch ~~ @{$archs{$type}});

	# Populate %results
	$results{$config} = {} unless $results{$config};
	$results{$config}{$type} = {} unless $results{$config}{$type};
	$results{$config}{$type}{$arch} = $result;
}

for my $job (@{Scheduler::list_jobs('build'=>$build)||[]}) {
	my $testname = $job->{'name'};
	my $p = openqa::parse_testname($testname);
	my $config = $p->{extrainfo};
	my $type = $p->{flavor};
	my $arch = $p->{arch};

	if ($job->{state} eq 'done') {
		my $result = test_result($testname);
		my $result_stats = test_result_stats($result);
		my $overall = "fail";
		if (($result->{overall}||'') eq "ok") {
			$overall = ($result->{dents}) ? "unknown" : "ok";
		}
		store_result($config, $type, $arch, { ok=>$result_stats->{ok}||0, unknown=>$result_stats->{unk}||0,
							fail=>$result_stats->{fail}||0, overall=>$overall, jobid=>$job->{id},
							state=>"done", testname=>$testname });
	} elsif ($job->{state} eq 'running') {
		store_result($config, $type, $arch, { state=>"running", testname=>$testname, jobid=>$job->{id} });
	} else {
		store_result($config, $type, $arch, { state=>$job->{state}, testname=>$testname,
							jobid=>$job->{id}, priority=>$job->{priority} });
	}
}

# Sorting everything
my @types = keys %archs;
@types = sort @types;
@configs = sort @configs;
for my $type (@types) {
	my @sorted = sort(@{$archs{$type}});
	$archs{$type} = \@sorted;
}

my $mt = Text::MicroTemplate::Extended->new(
	include_path  => ['../htdocs/template'],
	template_args => { build => $build, configs => \@configs, types => \@types, archs => \%archs, results => \%results }
);
print header(-charset=>"UTF-8", -type=>"text/html");
print $mt->render('buildview');
