#!/usr/bin/perl -w
use strict;
use FindBin;
use lib "$FindBin::Bin/modules";
use CGI ":standard";
use openqa;

my $fn=$ENV{PATH_INFO};
if($fn=~m/\.\./) {print header(-status=>403)."invalid path"; exit 0; }
$fn=~s%^/%%;
my($testname) = split(/\//, $fn);

my $results = test_result($testname);
unless ($results) { print header(-status=>404)."no testresults found"; exit 0; }

my $testmodule = $results->{'running'};
my $module = test_result_module($results->{'testmodules'}, $testmodule);
unless ($module) { print header(-status=>404)."running module not found"; exit 0; }
my $testindex = scalar(@{$module->{'details'}});

# Redirect to the right cropimg url
my $url = "/cropimg/show/$testname/$testmodule/$testindex";
print header(-status=>302, -location=>$url);
