#!/usr/bin/perl -w
use strict;
use CGI ":standard";
use lib "/usr/share/openqa/cgi-bin/modules";
use awstandard;
use openqa;

$| = 1;

my $pathinfo = $ENV{PATH_INFO};
$pathinfo=~s/^\///;
my ($testname,$diskimg) = split("/",$pathinfo);
$diskimg=~s/\.gz//;

my $basepath = back_log($testname);
if(!-d $basepath) { print header(-status=>404)."test not found in backlog"; exit 0 }

my $imgpath = "$basepath/$diskimg";
if(!-e $imgpath ) { print header(-status=>404)."test has no such diskimg"; exit 0 }

my $mtime=(stat($imgpath))[9];

print header(-charset=>"UTF-8", -type=>"application/x-gzip", -attachment => $testname.'_'.$diskimg.'.gz', -expires=>'+24h', -max_age=>'86400', -Last_Modified=>awstandard::HTTPdate($mtime));
exec('gzip', '-cnq1', $imgpath);
