#!/usr/bin/perl -w
use strict;
use CGI ":standard";
use Image::Magick;
use lib "/srv/www/cgi-bin/modules";
use awstandard;

my $p = new Image::Magick(depth=>8);
my $name=$ENV{PATH_INFO};
if($name=~m/\.\./) {print header(-status=>403)."invalid path"; exit 0; }
$name=~s/\.ppm$//;
my $fullname="/space/geekotest/opensuse/$name.ppm";
if (!-e $fullname) {print header(-status=>404)."file not found"; exit 0; }
$p->Read($fullname, depth=>8);

my $size=param("size");
if($size && $size=~m/^\d{1,3}x\d{1,3}$/) {
	$p->Resize($size); # make thumbnail
}

my $mtime=(stat($fullname))[9];

print header(-type=>"image/jpg", -expires=>'+30m', -max_age=>'20000', -Last_Modified=>awstandard::HTTPdate($mtime)).
      $p->ImageToBlob(magick=>'JPG', depth=>8, quality=>80);

