#!/usr/bin/perl -w

use strict;
use FindBin;
my $serverclass;
for my $i (qw/JSON::RPC::Legacy::Server::CGI JSON::RPC::Server::CGI/) {
	eval "use $i;";
	$serverclass = $i unless $@;
}
die $@ unless $serverclass;

use lib "$FindBin::Bin/modules";
use Makefile;

my $server = $serverclass->new;
	
$server->return_die_message(1);
$server->dispatch('Makefile')->handle();

# vim: syntax=perl
