#!/usr/bin/perl -w
use strict;
use CGI qw":standard";
use Time::HiRes qw(sleep);
use lib "/srv/www/cgi-bin/modules";
use awstandard;
use openqa;
#use File::Tail;



$| = 1;

$SIG{HUP} = sub { exit 0; };
$SIG{TERM} = sub { exit 0; };
$SIG{PIPE} = sub { exit 0; };

my $name=$ENV{PATH_INFO};

$name=~s/^\/(.*)/$1/;

my $basepath = running_log($name);

if($basepath eq '') {print header(-status=>404)."test not running"; exit 0; }

my $log = param('log') || '';
my $text = param('text') || '';


if($log eq 'current') {
	unless(-e $basepath.'currentstep') {print header(-status=>404)."test not running"; exit 0; }
	my (undef, $currentstep) = split(' ', file_content($basepath.'currentstep'));
	print header({-type=>"text/plain", Content_Encoding=>"none"});
	print $currentstep;
	exit;
}
elsif($log eq 'modlist') {
	unless(-e $basepath.'currentstep') {print header(-status=>404)."test not running"; exit 0; }
	my (undef, $currentstep) = split(' ', file_content($basepath.'currentstep'));
	print header({-type=>"text/html", Content_Encoding=>"none"});
	my $filecontent = file_content($basepath.'currentautoinst-log.txt') || '';
	my @modules = $filecontent=~m/^scheduling\s(\w+)\s\S+$/gm;
	my $found = 0;
	unless ($currentstep and grep(/^$currentstep$/, @modules)) {
		$found = 1;
	}
	my @modlist;
	foreach my $module (@modules) {
		my $out;
		my $omod = $module;
		if ($found) {
			#$out = '&#9679;';
			$out = '-';
		}
		elsif ($module=~m/^$currentstep$/) {
			$found = 1;
			#$out = '&#10148;';
			$out = '<b>&gt;</b>';
			$omod = "<b>$module</b>";
		}
		else {
			#$out = '&#10004;';
			$out = '&#10003;';
		}
		push(@modlist, "<tr><td>$out</td><td><a href='/tdata/show/$name/$module'>$omod</a></td></tr>");
	}


	print "<table>\n";
	print join("\n", @modlist);
	print "</table>\n";
	exit;
}

else {
	unless(-e $basepath.'currentautoinst-log.txt') {print header(-status=>404)."test not running"; exit 0; }
	#my $file=File::Tail->new($basepath.'currentautoinst-log.txt');
	alarm(7200);
	if ($text) {
		print header({-type=>"text/plain", Content_Encoding=>"none"});
	}
	else {
		print header({-type=>"text/html", Content_Encoding=>"none"});
		print "<style>pre { font-family: 'monospace', monospace; font-size: 12px; }</style><pre>";
	}
	system('tail', '-fn+0', $basepath.'currentautoinst-log.txt');
	exit;
}

