#!/usr/bin/perl -w
use strict;
use CGI ":standard";
use Image::Magick;

my $p = new Image::Magick(depth=>8);
my $name=$ENV{PATH_INFO};
if($name=~m/\.\./) {print header(-status=>403)."invalid path"; exit 0; }
$name=~s/\.ppm$//;
my $fullname="/space/geekotest/opensuse/$name.ppm";
if (!-e $fullname) {print header(-status=>404)."file not found"; exit 0; }
$p->Read($fullname, depth=>8);

my $size=param("size");
if($size && $size=~m/^\d{1,3}x\d{1,3}$/) {
	$p->Resize($size); # make thumbnail
}

print header("image/png").
      $p->ImageToBlob(magick=>'PNG', depth=>8);

