#!/usr/bin/perl -w
use strict;
use CGI ":standard";
use lib "/srv/www/cgi-bin/modules";
use awstandard;
#use sort_table;
use openqa;

sub imgfqfn_to_link($;$)
{ my($x,$wantthumb)=@_;
	my $name=$x;
	$name=~s/.*-(\d+)\.ppm/$1/;
	$x=~s{^$basedir(/opensuse.*)\.ppm}{$1.jpg};
	# add thumbnail inline img
	my $width=80; my $height=int($width/4*3);
	my $thumb=($wantthumb?qq(<img src="$x?size=${width}x${height}" width="${width}" height="${height}" alt="$name" />):"");
	qq(<a href="/viewimg$x">$name$thumb</a>);
}


my $fn=$ENV{PATH_INFO};
if(!defined $fn) { print header(-status=>404)."must specify result file as path"; exit 0 }
$fn=~s%^/%%;
if($fn=~/(?:\.\.)|[^a-zA-Z0-9._+-]/){ print header(-status=>"403 Forbidden")."Forbidden: invalid path"; exit 0 }
$fn=~s/\.autoinst\.txt$//; $fn=~s/\.ogv$//; # be tolerant in what we accept
my $resultdir="$basedir/opensuse/video";
my $imgdir=openqa::imgdir($fn);
my $fqfn="$resultdir/$fn.ogv.autoinst.txt";
if(!-e $fqfn) { print header(-status=>404)."file not found"; exit 0 }

my @fnsplit=split_filename($fqfn);
$fnsplit[0].=" ".openqa::path_to_loglink($fqfn);

my @lines=parse_log($fqfn);
my @timeouts=<$imgdir/timeout-[0-9]*.ppm>;
if(@timeouts) {unshift(@lines, ["timeout","unknown"])}
my @out=();
foreach my $entry (@lines) {
	my ($name,$result)=@$entry;
	my $wantthumb=($result!~m/OK/);
	# add link to $imgdir/$name*.ppm via png CGI
	my @imglist=map {imgfqfn_to_link($_,$wantthumb)} <$imgdir/$name-[0-9]*.ppm>;
	my $cssclass="\L$result";
	$cssclass=~s/\s.*//;
	my $component=$name;
	if(get_testimgs($name)) {
		$component='<a href="/refimgs/'.$name.'">'.$name.'</a>';
	}
	#$result=~s/\s.*//;
	$result=~s{(.*)\s\((.*)\)}{$1<br /><span class="subresults">$2</span>};
	push(@out, qq(<tr><td class="component">$component</td><td class='result$cssclass'>$result</td><td class="links">@imglist</td></tr>\n));
}

my ($header,$footer)=get_header_footer(qq{<a href="/results/">Results</a> &gt; $fn});
print header("text/html").
$header.
qq{
<p>This tool displays details on one particular test result.
<br/>
$fnsplit[0] <a href="/results/"><img src="/images/back.png" alt="back" title="back to overview page" /></a> 
</p>
<h2>results</h2>
<table>
@out
</table>}.
$footer;

