#!/usr/bin/perl -w
use strict;
use CGI qw":standard";
use JSON;
my $clientclass;
for my $i (qw/JSON::RPC::Legacy::Client JSON::RPC::Client/) {
	eval "use $i;";
	$clientclass = $i unless $@;
}
die $@ unless $clientclass;

my $url = param('url') || '';
my $method = param('method') || '';
my $json = param('params') || 0;
my $params;
my $callobj;
if ($json) {
	$params = decode_json($json);
	$callobj = { method => $method, params => $params };
} else {
	$callobj = { method => $method };
}

my $client = new $clientclass;
my $ret = $client->call($url, $callobj);
print header({-type=>"application/json", Content_Encoding=>"none"});
print $ret->{'jsontext'};
exit;
