#!/usr/bin/perl -w
use strict;
use CGI ":standard";
use FindBin;
use lib "$FindBin::Bin/modules";
use openqa;
use Text::MicroTemplate "encoded_string";
use Text::MicroTemplate::Extended;

my $testname=path_to_testname($ENV{PATH_INFO});
my $basepath = running_log($testname);
my $running = !($basepath eq '');

my $backend_info = parse_log_json($basepath.'autoinst-log.txt');

my $mt = Text::MicroTemplate::Extended->new(
	include_path  => ['../htdocs/template'],
	template_args => { testname => $testname, basepath => $basepath, running => $running, backend_info => $backend_info },
);

print header(-charset=>"UTF-8", -type=>"text/html");
print $mt->render('running');
