#!/usr/bin/perl -w
use strict;
use CGI ":standard";
use FindBin;
use lib "$FindBin::Bin/modules";
use openqa;
use Scheduler ();

my $name=$ENV{PATH_INFO};
$name=~s{^/}{};
$name=~s/[^a-zA-Z0-9.+_-]//g; # sanitize
$|=1;

my $back = param('redirect_back');
my $cancel = param('cancel');
if($back) {
	print header(-type=>"text/html");
	print "<script type='text/javascript'>\n";
}
else {
	print header(-type=>"text/plain");
}
$cancel = (defined $cancel and $cancel);

sub myprint($) {
	my $pr = shift;
	if($back) { print "alert(\"$pr\");\n" }
	else { print $pr }
}

if(!is_authorized_rw()) {
	myprint "denied";
}
else {
	if($cancel) {
	    Scheduler::job_stop($name);
	} else {
	    Scheduler::job_restart($name);
	}
}

if($back) {

	my $params = openqa::parse_testname($name);
	if($cancel || $back eq 'results') {
		print "window.location = '/results/';\n";
	} elsif ($back eq 'details') {
		print "window.location = '/results/$name';\n";
	} else {
		print "window.location = '/buildview/$params->{distri}/Build$params->{build}';\n";
	}
	print '</script>\n';
}
