#!/usr/bin/perl -w
use strict;
use CGI ":standard";
use FindBin;
use lib "$FindBin::Bin/modules";
use openqa;


my $up=param("upload");
my $testname=param("testname");

my $ip=$ENV{REMOTE_ADDR};
my %whitelist=(
	"127.0.0.1"=>1, # occurs for 10.0.2.2
);
if(!$whitelist{$ip}) {
	print header(-status=>403)."forbidden";
	exit 2;
}
#print header(),<$up>, $testname, $ENV{REQUEST_METHOD};

$testname=~s/(?:\.\.)|[^a-zA-Z0-9._+-]//g;
my $upname = $up;
$upname=~s#.*/##;
$upname=~s/(?:\.\.)|[^a-zA-Z0-9._+-]//g;
print header(),"OK: $testname -> $upname\n";
mkdir("/$prj/logupload/$testname");
chmod(0777, "/$prj/logupload/$testname");
my $file="/$prj/logupload/$testname/$upname";
open(my $out, ">", $file) or die "opening $file failed: $!";
while(<$up>) {
	print $out $_;
}

