#!/usr/bin/perl -w
use strict;
use CGI ":standard";
use lib "/srv/www/cgi-bin/modules";
use openqa;


my $up=param("upload");
my $testname=param("testname");

my $ip=$ENV{REMOTE_ADDR};
my %whitelist=(
	"127.0.0.1"=>1, # occurs for 10.0.2.2
);
if(!$whitelist{$ip}) {
	print header(-status=>403)."forbidden";
	exit 2;
}
#print header(),<$up>, $testname, $ENV{REQUEST_METHOD};

$testname=~s/(?:\.\.)|[^a-zA-Z0-9._+-]//g;
print header(),"OK: $testname\n";
my $file="/$prj/logs/$testname.tar.bz2";
open(my $out, ">", $file) or die "opening $file failed: $!";
while(<$up>) {
	print $out $_;
}

