---
name: check-containers
# yamllint disable-line rule:truthy
on: [push, pull_request]
jobs:
  static-check-containers:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Test our container definitions
        run: make test-check-containers
