---
# yamllint disable-line rule:truthy
on: [pull_request_target]
jobs:
  checklist_job:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    name: Checklist job
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - name: Checklist
        uses: wyozi/contextual-qa-checklist-action@dd4b6b51d85a59f537b7ca9e2f162164627ec811  # master
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          input-file: .github/checklist.yml
          include-hidden-files: true
