---
name: check-helm-chart
# yamllint disable-line rule:truthy
on: [push, pull_request]
jobs:
  lint-chart:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Install Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4
        with:
          version: v3.8.1

      - name: Install Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: 3.13

      - name: Set up chart-testing
        uses: helm/chart-testing-action@6ec842c01de15ebb84c8627d2744a0c2f2755c9f # v2

      - name: Run chart-testing
        run: make test-helm-lint
  install-chart:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    needs: lint-chart
    env:
      REGISTRY_PATH: registry.opensuse.org/devel/openqa/containers16.0
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Install Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4
        with:
          version: v3.8.1

      - name: Install Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: 3.13

      - name: Install retry
        run: |
          curl -sSfL https://raw.githubusercontent.com/okurz/retry/main/retry -o /usr/local/bin/retry
          chmod +x /usr/local/bin/retry

      - name: Set up chart-testing
        uses: helm/chart-testing-action@6ec842c01de15ebb84c8627d2744a0c2f2755c9f # v2

      - name: Create kind cluster
        uses: helm/kind-action@ef37e7f390d99f746eb8b610417061a60e82a6cc # v1

      - name: Download images
        run: |
          for i in webui worker; do
            retry -r 7 -s 15 -e docker pull $REGISTRY_PATH/openqa_$i:latest
          done

      - name: Load images into the Cluster
        run: |
          kind load docker-image --name chart-testing \
          $REGISTRY_PATH/openqa_webui:latest \
          $REGISTRY_PATH/openqa_worker:latest

      - name: Run chart-testing
        run: make test-helm-install
