---
name: compose
# yamllint disable-line rule:truthy
on: [push, pull_request]
jobs:
  webui-docker-compose:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - name: Verify that containers can be composed
        run: make test-containers-compose
